package com.chrynan.time

/**
 * Convenience utilities for converting between different time intervals.
 *
 * @author chRyNaN
 */
object TimeUtils {

    const val NANOSECONDS_IN_MICROSECOND = 1_000L
    const val MICROSECONDS_IN_MILLISECOND = 1_000L
    const val MILLISECONDS_IN_SECOND = 1_000L
    const val SECONDS_IN_MINUTE = 60L
    const val MINUTES_IN_HOUR = 60L
    const val HOURS_IN_DAY = 24L
    const val DAYS_IN_WEEK = 7L

    const val NANOSECONDS_IN_MILLISECOND = NANOSECONDS_IN_MICROSECOND * MICROSECONDS_IN_MILLISECOND
    const val NANOSECONDS_IN_SECOND = MILLISECONDS_IN_SECOND * NANOSECONDS_IN_MILLISECOND
    const val NANOSECONDS_IN_MINUTE = SECONDS_IN_MINUTE * NANOSECONDS_IN_SECOND
    const val NANOSECONDS_IN_HOUR = MINUTES_IN_HOUR * NANOSECONDS_IN_MINUTE
    const val NANOSECONDS_IN_DAY = HOURS_IN_DAY * NANOSECONDS_IN_HOUR
    const val NANOSECONDS_IN_WEEK = DAYS_IN_WEEK * NANOSECONDS_IN_DAY

    const val MICROSECONDS_IN_SECOND = MICROSECONDS_IN_MILLISECOND * MILLISECONDS_IN_SECOND
    const val MICROSECONDS_IN_MINUTE = SECONDS_IN_MINUTE * MICROSECONDS_IN_SECOND
    const val MICROSECONDS_IN_HOUR = MINUTES_IN_HOUR * MICROSECONDS_IN_MINUTE
    const val MICROSECONDS_IN_DAY = HOURS_IN_DAY * MICROSECONDS_IN_HOUR
    const val MICROSECONDS_IN_WEEK = DAYS_IN_WEEK * MICROSECONDS_IN_DAY

    const val MILLISECONDS_IN_MINUTE = SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND
    const val MILLISECONDS_IN_HOUR = MINUTES_IN_HOUR * MILLISECONDS_IN_MINUTE
    const val MILLISECONDS_IN_DAY = HOURS_IN_DAY * MILLISECONDS_IN_HOUR
    const val MILLISECONDS_IN_WEEK = DAYS_IN_WEEK * MILLISECONDS_IN_DAY

    const val SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE
    const val SECONDS_IN_DAY = HOURS_IN_DAY * SECONDS_IN_HOUR
    const val SECONDS_IN_WEEK = DAYS_IN_WEEK * SECONDS_IN_DAY

    const val MINUTES_IN_DAY = HOURS_IN_DAY * MINUTES_IN_HOUR
    const val MINUTES_IN_WEEK = DAYS_IN_WEEK * MINUTES_IN_DAY

    const val HOURS_IN_WEEK = DAYS_IN_WEEK * HOURS_IN_DAY
}